
name: CI

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test_job:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'commenttest')
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: hostname
        run: hostname